In [2]:
import numpy as np

# creating an array using Python lists
arr=[2,3,1]
np.array(arr)

array([2, 3, 1])

In [4]:
# creating an array of linearly-speced elements
# starting with 0, ending at 30 stepping by 3
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
# creating an array by dividing a range into a number of parts
# starting with 0 and ending at 10 divided into 5 elements
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
# creating a 2D array with normally distributed random values
# mean at 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-0.14987512, -1.18215038, -1.58571979],
       [ 1.76204813,  0.17311594,  0.09687449],
       [ 0.14049602,  0.30444836, -2.116034  ]])

In [9]:
## set a seed value to generate same random values on every run
np.random.seed(0)

# create 3 arrays(1D,2D,3D)
arr1=np.random.randint(10,size=6)
arr2=np.random.randint(10,size=(3,4))
arr3=np.random.randint(10,size=(3,4,5))

## printing the dimension, shape, size and bytes of an array
print("Arr3 dimension: ", arr3.ndim)
print("Arr3 shape: ",arr3.shape)
print("Arr3 size: ",arr3.size)
print("Arr3 bytes: ",arr3.nbytes," bytes")

Arr3 dimension:  3
Arr3 shape:  (3, 4, 5)
Arr3 size:  60
Arr3 bytes:  240  bytes


In [10]:
## defining 2 arrays and adding them as vectors
a=np.array([3,4,5])
b=np.array([5,6,7])

a+b

array([ 8, 10, 12])

In [11]:
# creating an array of 1s
one=np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# adding a 1D array tto a 2D array
one+a

array([[4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.]])

In [13]:
arr=np.array([10,5,20,100])
arr>=20

array([False, False,  True,  True])

In [14]:
# equivalent ufunc for the comparison operator
np.greater(arr,30)

array([False, False, False,  True])

In [18]:
# creating a 2D array of random integers with values <10
arr=np.random.randint(10,size=(3,4))
arr

array([[3, 2, 3, 4],
       [1, 2, 9, 1],
       [4, 6, 8, 2]])

In [19]:
# counting number of values that are greater than 5 using np.sum()
np.sum(arr>5)

3

In [20]:

# counting number of values that are greater than 5 in each row
np.sum(arr>5, axis=1)

array([0, 1, 2])

In [21]:
# math test scores of students in a class
test_scores=np.random.randint(100,size=(30))
test_scores

array([51, 80, 32, 54,  0, 38, 19, 46, 42, 56, 60, 77, 30, 24,  2,  3, 94,
       98, 13, 40, 72, 19, 95, 72, 26, 66, 52, 67, 61, 14])

In [23]:
# number of students who scored more than 50 but less than 75
np.sum((test_scores>50) & (test_scores<75))


10

In [24]:
# extracting all the indices which meet the condition
np.where((test_scores>50) & (test_scores<75))

(array([ 0,  3,  9, 10, 20, 23, 25, 26, 27, 28], dtype=int64),)

In [25]:
# extracting all the elements (values) that adhere to the mask
mask=test_scores>75
test_scores[mask]

array([80, 77, 94, 98, 95])

In [28]:
import numpy as np
import pandas as pd
import random
import string

# create a dictionary that stores
# students roll number, math, physics and chem scores
scores_dict={'id' : [''.join(random.choices(string.ascii_uppercase+string.digits,k=5))for _ in range(30)],
             'roll':np.arange(30)+1,
             'math_scores':np.random.randint(100,size=(30)),
             'physic_scores':np.random.randint(100,size=(30)), 
             'chemistry_scores':np.random.randint(100,size=(30))}

print(scores_dict)

{'id': ['35Y3D', 'CG5S8', 'FZE2H', 'APQ4L', 'LV6KO', 'AY5HX', 'Z0PZ7', 'GB9B9', 'SXKKM', 'XFAFK', '6X7WO', 'TNG1N', 'YXWIY', 'LBTF1', 'XHS5M', 'HHEZ1', 'YWV4B', 'VSMAX', 'R3UTE', 'GQVK0', 'GXZH2', '1I4HG', 'HI08M', 'MIUHE', '0BKEM', '1OSSE', 'CKH21', 'WEG3G', 'EZI7J', '64VOT'], 'roll': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 'math_scores': array([44, 34, 34, 88, 33,  5, 36,  0, 75, 34, 69, 53, 80, 62,  8, 61,  1,
       81, 35, 91, 40, 36, 48, 25, 67, 35, 30, 29, 33, 18]), 'physic_scores': array([17, 93, 84,  2, 69, 12, 44, 66, 91, 85, 39, 39, 75, 22, 30, 17, 70,
       71, 18, 92, 43, 83, 49, 41, 93, 46, 21, 73, 89, 96]), 'chemistry_scores': array([91, 73, 28, 81, 58,  0, 86, 63, 16, 36, 94, 24, 63, 67, 51,  8, 56,
       91, 93, 87, 32, 19, 72, 71, 87, 13, 58, 81, 55, 64])}


In [29]:
# convert the scores_dict to a pandas dataframe

df=pd.DataFrame(scores_dict)
df.head()

id  roll  math_scores  physic_scores  chemistry_scores
0  35Y3D     1           44             17                91
1  CG5S8     2           34             93                73
2  FZE2H     3           34             84                28
3  APQ4L     4           88              2                81
4  LV6KO     5           33             69                58

In [30]:
# make id column the index of the dataframe

df=df.set_index('id')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 35Y3D to 64VOT
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   roll              30 non-null     int32
 1   math_scores       30 non-null     int32
 2   physic_scores     30 non-null     int32
 3   chemistry_scores  30 non-null     int32
dtypes: int32(4)
memory usage: 720.0+ bytes


In [31]:
# acces individual columns

df.math_scores

id
35Y3D    44
CG5S8    34
FZE2H    34
APQ4L    88
LV6KO    33
AY5HX     5
Z0PZ7    36
GB9B9     0
SXKKM    75
XFAFK    34
6X7WO    69
TNG1N    53
YXWIY    80
LBTF1    62
XHS5M     8
HHEZ1    61
YWV4B     1
VSMAX    81
R3UTE    35
GQVK0    91
GXZH2    40
1I4HG    36
HI08M    48
MIUHE    25
0BKEM    67
1OSSE    35
CKH21    30
WEG3G    29
EZI7J    33
64VOT    18
Name: math_scores, dtype: int32

In [33]:
# access the 10th row
df.iloc[10]

roll                11
math_scores         69
physic_scores       39
chemistry_scores    94
Name: 6X7WO, dtype: int32