In [2]:
import numpy as np

# creating an array using Python lists
arr=[2,3,1]
np.array(arr)

array([2, 3, 1])

In [4]:
# creating an array of linearly-speced elements
# starting with 0, ending at 30 stepping by 3
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
# creating an array by dividing a range into a number of parts
# starting with 0 and ending at 10 divided into 5 elements
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
# creating a 2D array with normally distributed random values
# mean at 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-0.14987512, -1.18215038, -1.58571979],
       [ 1.76204813,  0.17311594,  0.09687449],
       [ 0.14049602,  0.30444836, -2.116034  ]])

In [9]:
## set a seed value to generate same random values on every run
np.random.seed(0)

# create 3 arrays(1D,2D,3D)
arr1=np.random.randint(10,size=6)
arr2=np.random.randint(10,size=(3,4))
arr3=np.random.randint(10,size=(3,4,5))

## printing the dimension, shape, size and bytes of an array
print("Arr3 dimension: ", arr3.ndim)
print("Arr3 shape: ",arr3.shape)
print("Arr3 size: ",arr3.size)
print("Arr3 bytes: ",arr3.nbytes," bytes")

Arr3 dimension:  3
Arr3 shape:  (3, 4, 5)
Arr3 size:  60
Arr3 bytes:  240  bytes


In [10]:
## defining 2 arrays and adding them as vectors
a=np.array([3,4,5])
b=np.array([5,6,7])

a+b

array([ 8, 10, 12])

In [11]:
# creating an array of 1s
one=np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# adding a 1D array tto a 2D array
one+a

array([[4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.]])